In [2]:
# 5.1 최적화 기초
# scipy를 사용한 최적화
# minimize(func, x0, jac=jac) jac는 옵션

In [3]:
def f1(x):
    return (x-2) ** 2+2


x0 = 0
result = sp.optimize.minimize(f1, x0)
result

      fun: 2.0
 hess_inv: array([[0.5]])
      jac: array([0.])
  message: 'Optimization terminated successfully.'
     nfev: 9
      nit: 2
     njev: 3
   status: 0
  success: True
        x: array([1.99999999])

In [8]:
# f1의 도함수
def f1p(x):
    return 2*(x-2)


x0 = 0
result = sp.optimize.minimize(f1, x0, jac=f1p)
result

      fun: 2.0
 hess_inv: array([[0.5]])
      jac: array([0.])
  message: 'Optimization terminated successfully.'
     nfev: 3
      nit: 2
     njev: 3
   status: 0
  success: True
        x: array([2.])

In [9]:
# 2차원 목적함수의 재정의 (벡터 입력을 받도록)
def f2(x):
    return (1-x[0])**2 + 100.0 * (x[1]-x[0]**2)**2


x0 = (-2, -2)
result = sp.optimize.minimize(f2, x0)
result

      fun: 5.2112890141803265e-12
 hess_inv: array([[0.49938636, 0.99860874],
       [0.99860874, 2.00187364]])
      jac: array([ 7.32138760e-05, -3.35902622e-05])
  message: 'Desired error not necessarily achieved due to precision loss.'
     nfev: 536
      nit: 55
     njev: 131
   status: 2
  success: False
        x: array([0.99999854, 0.9999969 ])

In [27]:
# 5.1.1 연습문제
# 1)
x0 = (-0.5, -0.302)
result = sp.optimize.minimize(f2, x0)
result

      fun: 2.021586744279839e-11
 hess_inv: array([[0.49994401, 0.99976708],
       [0.99976708, 2.00432672]])
      jac: array([-2.82535239e-06,  1.39424461e-06])
  message: 'Optimization terminated successfully.'
     nfev: 104
      nit: 19
     njev: 26
   status: 0
  success: True
        x: array([0.9999955 , 0.99999101])

In [52]:
# 그레이디언트 벡터 구하기 심파이로
import sympy
x, y = sympy.symbols('x y')
f = (1-x)**2 + 100.0 * (y-x**2)**2
a = sympy.diff(f, x)
b = sympy.diff(f, y)
a, b

(-400.0*x*(-x**2 + y) + 2*x - 2, -200.0*x**2 + 200.0*y)

In [59]:
# 2) 그레디언트 벡터를 함수로 작성, x = x[0], y = x[1]
def f2g(x):
    return np.array([-400 * x[0]*(-x[0]**2+x[1])+2*x[0]-2, -200*x[0]**2+200*x[1]])


x0 = (0, 0)
result = sp.optimize.minimize(f2, x0, jac=f2g)
result

      fun: 7.717288542643934e-13
 hess_inv: array([[0.49480256, 0.98953879],
       [0.98953879, 1.98387918]])
      jac: array([ 3.92841203e-06, -2.83120875e-06])
  message: 'Optimization terminated successfully.'
     nfev: 24
      nit: 19
     njev: 24
   status: 0
  success: True
        x: array([0.99999913, 0.99999825])

In [60]:
# 5.2 제한조건이 있는 최적화 문제

In [2]:
# 사이파이를 사용하여 등식제한조건이있는 최적화 문제 계산하기
# fmin_slsqp(func_objective, x0, eqcons = [func_constraint1,func_constraint2])
# func_objective = 목적함수
# x0 = 초기값
# func_constraint = 제한조건 함수


def f1array(x):
    return x[0] ** 2 + x[1] ** 2


def eq_constraint(x):
    return x[0] + x[1] - 1


sp.optimize.fmin_slsqp(f1array, np.array([1, 1]), eqcons=[eq_constraint])

Optimization terminated successfully.    (Exit mode 0)
            Current function value: 0.5000000000000002
            Iterations: 2
            Function evaluations: 8
            Gradient evaluations: 2


array([0.5, 0.5])

In [4]:
# 사이파이를 사용하여 부등식제한조건이있는 최적화 문제 계산하기
# fmin_slsqp(func_objective, x0, eqcons = [func_constraint1,func_constraint2])
# func_objective = 목적함수
# x0 = 초기값
# ieqcons = [func_constraint] = 제한조건 함수
# 부등호는 g >= 0


def f2(x):
    return np.sqrt((x[0]-4)**2+(x[1]-2)**2)


# 제한조건 상수
k = 1


def ieq_constrait(x):
    return np.atleast_1d(k - np.sum(np.abs(x)))


sp.optimize.fmin_slsqp(f2, np.array([0, 0]), ieqcons=[ieq_constrait])

Optimization terminated successfully.    (Exit mode 0)
            Current function value: 3.605551280732028
            Iterations: 11
            Function evaluations: 77
            Gradient evaluations: 11


array([9.99999981e-01, 1.89941792e-08])

In [4]:
# 연습문제 5.2.4
def f2(x):
    return np.sqrt((x[0]-4)**2 + (x[1]-2)**2)

# 제한조건 상수
k = 3
def ieq_constraint(x):
    return np.atleast_1d(k-np.sum(np.abs(x)))

sp.optimize.fmin_slsqp(f2, np.array([0,0]), ieqcons=[ieq_constraint])

Optimization terminated successfully.    (Exit mode 0)
            Current function value: 2.1213203438762323
            Iterations: 6
            Function evaluations: 24
            Gradient evaluations: 6


array([2.4999741, 0.5000259])

In [10]:
# 5.3 선형계획법 문제와 이차계획법 문제
# 제품 A와 제품B를 각 100개 이상 생산
# 시간은 500시간
# 제품 A는 생산 1시간, 제품B는 2시간
# 부품은 9800개
# 제품 A는 부품 4개, 제품B는 부품 5개
# 제품 A는 3만원이익 제품B는 5만원 이익

A = np.array([[-1, 0], [0, -1], [1, 2], [4, 5]])  # x 앞의 조건
b = np.array([-100, -100, 500, 9800])  # 조건
c = np.array([-3, -5])  # x의 이익

result = sp.optimize.linprog(c, A, b)
result

     con: array([], dtype=float64)
     fun: -1399.999994807384
 message: 'Optimization terminated successfully.'
     nit: 6
   slack: array([1.99999991e+02, 4.19920389e-06, 3.31137414e-07, 8.10000001e+03])
  status: 0
 success: True
       x: array([299.99999127, 100.0000042 ])

In [5]:
# CVXPY를 이용한 선형 계획법 계산
import cvxpy as cp

# 변수의 정의 -> 심볼릭 연산을 함
a = cp.Variable()  # a의 생산량
b = cp.Variable()  # b의 생산량

# 조건의 정의

constraints = [
    a >= 100,  # 제품a를 100개이상 생산
    b >= 100,  # 제품b를 100개이상 생산
    a + 2 * b <= 500,  # 500시간 이내에 생산
    4 * a + 5 * b <= 9800  # 부품은 9800개
]

# 문제의 정의

obj = cp.Maximize(3 * a + 5 * b)  # 해당의 최대화
prob = cp.Problem(obj, constraints)

# 계산

prob.solve()

# 결과
prob.status, a.value, b.value

('optimal', array(300.), array(100.))

In [10]:
# 이차 계획법 문제
# cvxopt를 이용한 이차계획법 문제 계산
from cvxopt import matrix, solvers

Q = matrix(np.diag([2.0, 2.0]))  # np.array 대신 matrix를, 숫자는 실수로
c = matrix(np.array([0.0, 0.0]))
A = matrix(np.array([[1.0, 1.0]]))
b = matrix(np.array([[1.0]]))

sol = solvers.qp(Q, c, A=A, b=b)
np.array(sol['x'])

array([[0.5],
       [0.5]])