### summary
- numpy : 선형대수를 빠르게 연산해주는 패키지
- 행렬의 생성 1 : ndarray data 타입으로 생성 (np.array, iteralbe)
- 헹렬의 생성 2 : ones(항등행렬), zeros(영행렬)
- 행렬 데이터 선택 : array[x,y,z] 바깥쪽 차원부터 안쪽 차원으로 선택
- 행렬 데이터 수정
    - 행렬 데이터를 선택 후
    - =, >(할당연산자) 값(scala, vector, matrix)
    - 브로드 캐스팅 개념 : 3x3 행렬 * 3x1 벡터는 벡터와 행렬이 인덱스에맞게 연산됨
- arange : list에서 사용하는 range와 같으나, 결과가 ndarray 타입으로 생성됨

### Quiz 
- 100 ~ 130까지 랜덤한 숫자를 가지는  8 * 8 행렬을 만들고,
- 3의 배수는 fiz, 5의 배수는 buz, 3과 5의 배수는 fbz 문자로 변환
- 랜덤 행렬 데이터 생성

```
datas = np.random.randint(100,130, size=(8,8))
```

- 데이터 타입이 정수이므로 문자열로 바꿔줘야함(ndarray.astype())

In [17]:
datas = np.random.randint(100,130, size=(8,8))

In [24]:
data1 = np.array([1, 2, 3])
data2 = [True, False, True]
data1[data2] # True만 남음

array([1, 3])

In [36]:
# 3의배수, 5의배수, 15의 배수 위치값에 대한 True, False matrix 생성
idx3 = datas % 3 == 0
idx5 = datas % 5 == 0
idx15 = datas % 15 == 0

# 데이터의 타입을 str로 변환
result = datas.astype("str")
# True, False matrix를 이용하여 특정 조건의 데이터를 선택 후 브로드 캐스팅하게 값을 대입
result[idx3] = "fiz"
result[idx5] = "buz"
result[idx15] = "fbz"
result

array([['107', '124', 'fiz', '118', 'fbz', 'fiz', 'fiz', 'fiz'],
       ['fiz', '113', '119', 'buz', 'fiz', '119', '128', '112'],
       ['fiz', 'buz', 'fiz', '107', '124', 'buz', '127', '112'],
       ['104', '127', '109', 'fbz', '112', '103', 'buz', 'fiz'],
       ['118', '127', 'fiz', '119', '106', 'buz', 'buz', '124'],
       ['104', 'fbz', 'fiz', 'fiz', 'fbz', '109', '106', '128'],
       ['buz', '116', '122', 'buz', '113', '121', '128', '104'],
       ['106', 'fbz', 'fiz', 'fiz', 'fiz', 'buz', 'fbz', '104']],
      dtype='<U11')

### Quiz
- 1 ~ 20까지 랜덤한 숫자를 가지는 5 * 5행렬 생성
- 최대값에는 MAX, 최소값에는 MIN 문자열이 들어가도록 치환하는 코드
- 최대값과 최소값 함수는
```
np.min(ndarray), np.max(ndarray)
```

In [41]:
datas = np.random.randint(1,20, (5,5))
datas

array([[13, 14,  2, 16, 19],
       [ 7,  2, 11,  3, 10],
       [ 7, 14,  4, 10,  9],
       [ 1,  6, 15, 19, 19],
       [18,  6,  4,  9,  8]])

In [42]:
#min_num, max_num 찾기
min_num, max_num = np.min(datas), np.max(datas)
min_num, max_num

(1, 19)

In [58]:
idx_min = datas == min_num # min을 True로 변환하여 해당 위치를 idx_ min에 저장함
idx_max = datas == max_num # max을 True로 변환하여 해당 위치를 idx_ max에 저장함
result = datas.astype("str") # result로 저장해주어야 함 astype는 저장기능이없음
result[idx_min] = "min"
result[idx_max] = "max"
result

array([['13', '14', '2', '16', 'max'],
       ['7', '2', '11', '3', '10'],
       ['7', '14', '4', '10', '9'],
       ['min', '6', '15', 'max', 'max'],
       ['18', '6', '4', '9', '8']], dtype='<U11')

### 1. inspace, logspace
- linsapce(선형적으로 데이터 자름) : 설정한 범위에서 선형적으로 분할한 위치의 값을 출력
- logsapce(로그로 데이터를 자름) : 설정한 범위에서 로그로 분할한 위치의 값을 출력

In [61]:
# linspace
np.linspace(0, 100, 5) # start, stop, num 순서

array([  0.,  25.,  50.,  75., 100.])

In [64]:
# logspace
# log10(x1) = 2, log10(x2) = 3, log10(x3) = 4 지수함수 그래프가 그려짐
np.logspace(2, 4, 3) # x1, x2, x3 순서

array([  100.,  1000., 10000.])

In [65]:
# 30세에 연봉이 $100000 이고 60세의 연봉이 & 1000000 일때
# 연봉이 선형으로 증가, 지수함수로 증가하는 두 경우에서의 40세, 50세 연봉을 출력

In [67]:
age_30 = 100000
age_60 = 10000000

In [68]:
# 선형으로 증가
np.linspace(age_30,age_60, 4)

array([  100000.,  3400000.,  6700000., 10000000.])

In [69]:
# 지수함수로 증가하는 경우
np.logspace(np.log10(age_30), np.log10(age_60),4)

array([  100000.        ,   464158.88336128,  2154434.69003188,
       10000000.        ])

### 2. numpy random - 마지막 숫자가 들어가지 않음
- seed : 랜덤값을 설정하는 값 (똑같이 섞음)
- rand : 균등분포로 난수를 발행 (뽑힐 확률이 동일함 주사위 눈)
- randn : 정규분포로 난수를 발행 (종모양, 0에서 가까운 데이터가 생성될 확률이 높음, 특이값)
- randint : 균등분포로 정수값을 발생
- suffle : 행렬 데이터를 섞어줌
- choice : 특정 확률로 데이터를 선택

In [71]:
# seed
np.random.seed(1) # numpy 객체의 seed값을 1로 설정함
result1 = np.random.randint(10, 100, 10)

np.random.seed(1) # numpy 객체의 seed값을 1로 설정함
result2 = np.random.randint(10, 100, 10)

np.random.seed(2) # numpy 객체의 seed값을 3로 설정함
result3 = np.random.randint(10, 100, 10)

result1, result2, result3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]))

In [73]:
# rand
# 0  ~ 1 까지의 숫자가 10으로 나눈 범위 (ex :0.0 ~ 0.1)에서 비슷한 갯수로(확률) 뽑힘
np.random.rand(10) 

array([0.85397529, 0.49423684, 0.84656149, 0.07964548, 0.50524609,
       0.0652865 , 0.42812233, 0.09653092, 0.12715997, 0.59674531])

In [74]:
# randn
# -1 ~ 1사이 숫자가 생성되며, 0에 가까운 수가 많이 생성됨 == 정규분포를 따름
np.random.randn(10)

array([-0.33882197, -0.23618403, -0.63765501, -1.18761229, -1.42121723,
       -0.1534952 , -0.26905696,  2.23136679, -2.43476758,  0.1127265 ])

In [79]:
# shuffle
r = np.random.randint(1, 10, (3, 4))
r

array([[6, 9, 4, 1],
       [1, 6, 8, 6],
       [1, 9, 7, 6]])

In [92]:
np.random.shuffle(r)
r # 행벡터만 순서가 바뀜 , 모두 바꾸고 싶다면 np.reshape을 사용

array([[1, 9, 7, 6],
       [1, 6, 8, 6],
       [6, 9, 4, 1]])

In [96]:
# choice
# 0 ~ 4까지의 5개의 숫자를 10개 뽑으며, p(확률값) 조정,p값은 sum(1)을 넘을수가 없다
np.random.choice(5, 10, p=[0.1, 0, 0.4, 0.2, 0.3])

array([4, 4, 3, 2, 4, 3, 2, 2, 4, 2], dtype=int64)

In [98]:
# unipue 유일한 값들을 뽑는 함수
# r에서 유니크한 값들을 뽑음
np.unique(r)

array([1, 4, 6, 7, 8, 9])

In [100]:
# return_counts = True로 유니크한 값이 몇번 나왔는지 count 해줌
numbers, counts = np.unique(r, return_counts=True)
print(numbers)
print(counts)
# [1 4 6 7 8 9]
# [3 1 4 1 1 2] 1이 3번, 4가 1번 6이 4번 ...

[1 4 6 7 8 9]
[3 1 4 1 1 2]


### 3. 행렬 데이터의 결합
- concatenate

In [102]:
na1 = np.random.randint(10, size = (2, 3))
na2 = np.random.randint(10, size = (3, 2))
na3 = np.random.randint(10, size = (3, 3))

In [105]:
na1

array([[5, 9, 2],
       [0, 0, 4]])

In [106]:
na2

array([[6, 3],
       [1, 8],
       [5, 9]])

In [107]:
na3

array([[5, 4, 2],
       [7, 8, 7],
       [3, 4, 8]])

In [109]:
# 세로 결합 (row가 추가됨) (column의 갯수가 같아야함)
np.concatenate((na1,na3))

array([[5, 9, 2],
       [0, 0, 4],
       [5, 4, 2],
       [7, 8, 7],
       [3, 4, 8]])

In [112]:
# 가로 결합 (column이 추가됨) (row의 갯수가 같아야함, axis = 1을 넣어줘야 함)
np.concatenate((na2, na3), axis = 1)

array([[6, 3, 5, 4, 2],
       [1, 8, 7, 8, 7],
       [5, 9, 3, 4, 8]])

In [114]:
# c_, r_로도 결합이 가능함
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [115]:
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

In [116]:
# 그 외 힘수들, mean, split....